### ISSUE TITLE
Cleanup workers automatically after a configurable "abandoned" time

### ISSUE THREAD

**Issue by galenatjpl** [NASA-AMMOS/common-workflow-service#43]
There should be a configurable workerAbandonTime setting.
Once a worker is dead for greater than this setting, it should be a candidate for automatic removal from the database.
Other tables that need to be cleaned up (for example the proc def tables) could be cascaded in this cleanup as well.

NOTE:  Issue #7  would have to be completed before this ticket.

**Comment by galenatjpl** [comment]
Rough time estimate:  1 day

**Comment by galenatjpl** [comment]
![Screen Shot 2021-12-08 at 3 54 24 PM](https://user-images.githubusercontent.com/47542238/145455073-e8c987df-e59f-41bd-8fb5-865e23f7a6f5.png)
@ztaylor54  That is the current approach, and it's run periodically/automatically via a crobjob.  This cronjob is setup by the mission, and is external to CWS core.  This ticket is about automating it in CWS core, which will be a better approach.

**Comment by voxparcxls** [comment]
Jira ticket: https://jira.jpl.nasa.gov/browse/CWS-647

**Comment by jamesfwood** [comment]
Closed in v2.2
