### ISSUE TITLE
External Elasticsearch SSL/auth issue

### ISSUE THREAD

**Issue by ztaylor54** [NASA-AMMOS/common-workflow-service#63]
CWS supports either connecting to Elasticsearch with no username and password via HTTP, or to Elasticsearch with username and password through HTTPS. The case where Elasticsearch is deployed with an SSL certificate (HTTPS), but without authentication, is not supported, and it seems to be a legitimate one (for example, Elasticsearch deployed on AWS within a restricted VPC).

# Intended / desired behavior:

 1. default to SSL, add config option for "elasticsearch_insecure" or something sensible

 2. if auth is provided (user/pass), pass it through, otherwise leave it out

 

so the "elasticsearchUseAuth" flag probably changes meaning in the code

 

# ideas / places to look:

 - rest service (makes lots of ES calls)

 - configuration (installer, etc) because that's where the user can set config options

 - will need to look into Spring autowiring, or at least just know where / when to use it (it's already how "elasticsearchUseAuth" gets passed around)

 - will probably need to run a local ES & mess around with different auth & cert settings

**Comment by jamesfwood** [comment]
Fixed in v2.2
